2012/06/22 20:17:54 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 20:19:45 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 20:22:30 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 20:22:46 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 20:33:45 [error] [php] require(C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php) [<a href='function.require'>function.require</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php:344)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 20:47:11 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 20:47:32 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 20:48:07 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 20:50:09 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 20:50:11 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 20:53:32 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 20:59:49 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 21:02:32 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 21:02:58 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 21:15:00 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 21:15:55 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 21:21:30 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 21:26:37 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 21:26:39 [error] [php] include(C:\xampp\htdocs\mybackbone\protected\components\Controller.php) [<a href='function.include'>function.include</a>]: failed to open stream: Permission denied (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(344): require()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(270): CWebApplication->createController()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 22:08:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "app_clean".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(271): CController->missingAction('app_clean')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(276): CController->run('app_clean')
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('site/app_clean/...')
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/mybackbone/index.php/site/app_clean/js/main.js
HTTP_REFERER=http://localhost/mybackbone/index.php/site/index
---
2012/06/22 22:09:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "app_clean".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(271): CController->missingAction('app_clean')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(276): CController->run('app_clean')
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('site/app_clean/...')
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/mybackbone/index.php/site/app_clean/js/main.js
HTTP_REFERER=http://localhost/mybackbone/index.php/site/index
---
2012/06/22 22:12:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "app_clean".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(271): CController->missingAction('app_clean')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(276): CController->run('app_clean')
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('site/app_clean/...')
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/mybackbone/site/app_clean/js/main.js
HTTP_REFERER=http://localhost/mybackbone/site/index
---
2012/06/22 22:14:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "app_clean".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(271): CController->missingAction('app_clean')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(276): CController->run('app_clean')
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('site/app_clean/...')
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/mybackbone/site/app_clean/js/main.js
HTTP_REFERER=http://localhost/mybackbone/site/index
---
2012/06/22 22:15:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "app_clean".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(271): CController->missingAction('app_clean')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(276): CController->run('app_clean')
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('site/app_clean/...')
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/mybackbone/site/app_clean/js/main.js
HTTP_REFERER=http://localhost/mybackbone/site/index
---
2012/06/22 22:17:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "app_clean".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(271): CController->missingAction('app_clean')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(276): CController->run('app_clean')
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('site/app_clean/...')
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/mybackbone/site/app_clean/js/main.js
HTTP_REFERER=http://localhost/mybackbone/site/index
---
2012/06/22 22:18:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "app_clean".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(271): CController->missingAction('app_clean')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(276): CController->run('app_clean')
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('site/app_clean/...')
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/mybackbone/site/app_clean/js/main.js
HTTP_REFERER=http://localhost/mybackbone/site/index
---
2012/06/22 22:44:16 [error] [php] include(bCrypt.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\components\UserIdentity.php(30): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(84): UserIdentity->authenticate()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(309): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CFilterChain.php(134): SiteController->runAction()
#5 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(1146): CAccessControlFilter->filter()
#7 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CInlineFilter.php(59): SiteController->filterAccessControl()
#8 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#9 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(266): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(276): SiteController->run()
#12 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#13 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/api/site/login
in C:\xampp\htdocs\mybackbone\protected\components\UserIdentity.php (30)
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (84)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 22:47:12 [error] [php] include(bCrypt.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\components\UserIdentity.php(30): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(84): UserIdentity->authenticate()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(309): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CFilterChain.php(134): SiteController->runAction()
#5 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(1146): CAccessControlFilter->filter()
#7 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CInlineFilter.php(59): SiteController->filterAccessControl()
#8 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#9 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(266): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(276): SiteController->run()
#12 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#13 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/api/site/login
in C:\xampp\htdocs\mybackbone\protected\components\UserIdentity.php (30)
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (84)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 23:03:28 [error] [php] include(bCrypt.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\components\UserIdentity.php(30): spl_autoload_call()
#1 C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php(84): UserIdentity->authenticate()
#2 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#3 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(309): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CFilterChain.php(134): SiteController->runAction()
#5 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(1146): CAccessControlFilter->filter()
#7 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CInlineFilter.php(59): SiteController->filterAccessControl()
#8 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#9 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CController.php(266): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(276): SiteController->run()
#12 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#13 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\mybackbone\index.php(13): CWebApplication->run()
REQUEST_URI=/mybackbone/api/site/login
in C:\xampp\htdocs\mybackbone\protected\components\UserIdentity.php (30)
in C:\xampp\htdocs\mybackbone\protected\controllers\SiteController.php (84)
in C:\xampp\htdocs\mybackbone\index.php (13)
2012/06/22 23:04:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/site/login".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('api/site/login')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/mybackbone/api/site/login
---
2012/06/22 23:08:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "app_clean/js/order.js".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('app_clean/js/or...')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/mybackbone/app_clean/js/order.js
HTTP_REFERER=http://localhost/mybackbone/
---
2012/06/25 01:01:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "app_clean/js/order.js".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('app_clean/js/or...')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/mybackbone/app_clean/js/order.js
HTTP_REFERER=http://localhost/mybackbone/
---
2012/06/25 01:01:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "app_clean/js/order.js".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('app_clean/js/or...')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/mybackbone/app_clean/js/order.js
---
2012/06/25 01:37:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "app_clean/js/order.js".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('app_clean/js/or...')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/mybackbone/app_clean/js/order.js
---
2012/06/25 01:37:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "app_clean/js/order.js".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('app_clean/js/or...')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/mybackbone/app_clean/js/order.js
HTTP_REFERER=http://localhost/mybackbone/
---
2012/06/25 16:49:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "app_clean/js/order.js".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('app_clean/js/or...')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/mybackbone/app_clean/js/order.js
HTTP_REFERER=http://localhost/mybackbone/
---
2012/06/25 17:00:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "app_clean/js/order.js".' in C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('app_clean/js/or...')
#1 C:\xampp\htdocs\mybackbone\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\mybackbone\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/mybackbone/app_clean/js/order.js
HTTP_REFERER=http://localhost/mybackbone/
---
2012/06/25 17:17:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'myslabdb'' in C:\xampp\htdocs\newback\protected\lib\yiiframework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\newback\protected\lib\yiiframework\cli\commands\MigrateCommand.php(419): CModule->getComponent('db')
#4 C:\xampp\htdocs\newback\protected\lib\yiiframework\cli\commands\MigrateCommand.php(427): MigrateCommand->getDbConnection()
#5 C:\xampp\htdocs\newback\protected\lib\yiiframework\cli\commands\MigrateCommand.php(458): MigrateCommand->getMigrationHistory(-1)
#6 C:\xampp\htdocs\newback\protected\lib\yiiframework\cli\commands\MigrateCommand.php(75): MigrateCommand->getNewMigrations()
#7 [internal function]: MigrateCommand->actionUp(Array)
#8 C:\xampp\htdocs\newback\protected\lib\yiiframework\console\CConsoleCommand.php(141): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#9 C:\xampp\htdocs\newback\protected\lib\yiiframework\console\CConsoleCommandRunner.php(65): CConsoleCommand->run(Array)
#10 C:\xampp\htdocs\newback\protected\lib\yiiframework\console\CConsoleApplication.php(91): CConsoleCommandRunner->run(Array)
#11 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CConsoleApplication->processRequest()
#12 C:\xampp\htdocs\newback\protected\lib\yiiframework\yiic.php(33): CApplication->run()
#13 C:\xampp\htdocs\newback\protected\yiic.php(7): require_once('C:\xampp\htdocs...')
#14 C:\xampp\htdocs\newback\protected\yiic(4): require_once('C:\xampp\htdocs...')
#15 {main}
---
2012/06/25 17:18:51 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myslapdb.tbl_migration' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `tbl_migration`.
2012/06/25 18:32:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "app_clean/js/order.js".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('app_clean/js/or...')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/app_clean/js/order.js
HTTP_REFERER=http://localhost/newback/
---
2012/06/25 19:02:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "heyo".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('heyo')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/heyo
HTTP_REFERER=http://localhost/newback/
---
2012/06/25 19:04:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "build/1".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('build/1')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/build/1
---
2012/06/25 19:04:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "app_clean/js/order.js".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('app_clean/js/or...')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/app_clean/js/order.js
HTTP_REFERER=http://localhost/newback/
---
2012/06/25 22:10:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/collection".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('api/collection')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/api/collection
---
2012/06/25 22:26:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/build".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('api/build')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/api/build
HTTP_REFERER=http://localhost/newback/
---
2012/06/25 22:28:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/build".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('api/build')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/api/build
HTTP_REFERER=http://localhost/newback/
---
2012/06/25 22:29:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/build".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('api/build')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/api/build
HTTP_REFERER=http://localhost/newback/
---
2012/06/25 22:30:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "build/create".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('build/create')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/build/create
HTTP_REFERER=http://localhost/newback/
---
2012/06/25 22:30:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "build/create".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('build/create')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/build/create
---
2012/06/25 22:31:40 [error] [php] Undefined variable: data (C:\xampp\htdocs\newback\protected\controllers\MindMapController.php:32)
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\filters\CFilterChain.php(134): MindmapController->runAction()
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\filters\CFilter.php(41): CFilterChain->run()
#2 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CController.php(1146): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\filters\CInlineFilter.php(59): MindmapController->filterAccessControl()
#4 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#5 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CController.php(266): MindmapController->runActionWithFilters()
#7 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(276): MindmapController->run()
#8 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController()
#9 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newback\index.php(13): CWebApplication->run()
REQUEST_URI=/newback/mindmap/create
in C:\xampp\htdocs\newback\protected\controllers\MindMapController.php (32)
in C:\xampp\htdocs\newback\index.php (13)
2012/06/25 22:33:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/mindmap".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('api/mindmap')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/api/mindmap
---
2012/06/25 22:33:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/build".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('api/build')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/api/build
---
2012/06/25 22:33:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "build".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('build')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/build
---
2012/06/25 22:34:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "build/index".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('build/index')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/build/index
---
2012/06/25 22:34:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "build/index".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('build/index')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/build/index
---
2012/06/25 22:34:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "build/index".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('build/index')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/index.php/build/index
---
2012/06/25 22:37:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newback/gii
---
2012/06/25 22:39:10 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "C:\xampp\htdocs\newback\assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CAssetManager.php:116
Stack trace:
#0 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CAssetManager.php(101): CAssetManager->setBasePath('C:\xampp\htdocs...')
#1 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CAssetManager.php(219): CAssetManager->getBasePath()
#2 C:\xampp\htdocs\newback\protected\lib\yiiframework\gii\GiiModule.php(139): CAssetManager->publish('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CComponent.php(112): GiiModule->getAssetsUrl()
#4 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CModule.php(106): CComponent->__get('assetsUrl')
#5 C:\xampp\htdocs\newback\protected\lib\yiiframework\gii\views\layouts\main.php(5): CModule->__get('assetsUrl')
#6 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\widgets\CContentDecorator.php(77): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\widgets\CContentDecorator.php(55): CContentDecorator->decorate('<div class="con...')
#10 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\widgets\COutputProcessor.php(45): CContentDecorator->processOutput('<div class="con...')
#11 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CBaseController.php(207): COutputProcessor->run()
#12 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CBaseController.php(301): CBaseController->endWidget('CContentDecorat...')
#13 C:\xampp\htdocs\newback\protected\lib\yiiframework\gii\views\layouts\column1.php(7): CBaseController->endContent()
#14 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#15 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#16 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CController.php(785): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#17 C:\xampp\htdocs\newback\protected\lib\yiiframework\gii\controllers\DefaultController.php(47): CController->render('login', Array)
#18 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\actions\CInlineAction.php(50): DefaultController->actionLogin()
#19 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CController.php(309): CInlineAction->runWithParams(Array)
#20 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#21 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(276): CController->run('login')
#23 C:\xampp\htdocs\newback\protected\lib\yiiframework\web\CWebApplication.php(135): CWebApplication->runController('gii/default/log...')
#24 C:\xampp\htdocs\newback\protected\lib\yiiframework\base\CApplication.php(162): CWebApplication->processRequest()
#25 C:\xampp\htdocs\newback\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/newback/index.php/gii/default/login
---
